# XcodeGen project specification for SDF Viewer Mobile
# Generate with: ./generate-project.sh (sets defaults) or via Makefile
# Install xcodegen: brew install xcodegen
#
# Environment variables (set by generate-project.sh or Makefile):
#   JANK_SRC - Path to jank compiler+runtime
#              Default: /Users/pfeodrippe/dev/jank/compiler+runtime

name: SdfViewerMobile

options:
  bundleIdPrefix: com.vybe
  deploymentTarget:
    iOS: "17.0"  # Required for jank C++20 features (std::format)
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: SdfViewerMobile
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "937QJHK26U"
    CODE_SIGN_STYLE: Automatic
    ENABLE_BITCODE: NO
    CLANG_CXX_LANGUAGE_STANDARD: c++20
    CLANG_CXX_LIBRARY: libc++
    GCC_PREPROCESSOR_DEFINITIONS:
      - VK_USE_PLATFORM_IOS_MVK=1
      - VK_USE_PLATFORM_METAL_EXT=1
      - JANK_TARGET_IOS=1
      - JANK_TARGET_WASM=1
      - JANK_TARGET_EMSCRIPTEN=1
      - IMMER_HAS_LIBGC=1
      - IMMER_TAGGED_NODE=0
      - SDF_AOT_BUILD=1

targets:
  SdfViewerMobile:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: main.mm
        compilerFlags: ["-x", "objective-c++"]
      - path: sdf_viewer_ios.mm
        compilerFlags: ["-x", "objective-c++"]
      # ImGui sources
      - path: ../vendor/imgui/imgui.cpp
      - path: ../vendor/imgui/imgui_draw.cpp
      - path: ../vendor/imgui/imgui_widgets.cpp
      - path: ../vendor/imgui/imgui_tables.cpp
      - path: ../vendor/imgui/backends/imgui_impl_vulkan.cpp
      - path: ../vendor/imgui/backends/imgui_impl_sdl3.cpp
      # STB implementation
      - path: ../vulkan/stb_impl.c
      # SDF engine implementation (compiled once to avoid duplicate symbols)
      - path: sdf_engine_impl.cpp
        compilerFlags: ["-x", "c++"]
      # jank AOT-compiled modules - linked as pre-compiled objects (see OTHER_LDFLAGS)
      # generated/vybe_sdf_generated.cpp is compiled by build_ios_jank_aot.sh
      # Resources (bundled with app)
      - path: LaunchScreen.storyboard
        buildPhase: resources
      - path: vulkan_kim
        buildPhase: resources
        type: folder
      - path: exported_scene.glb
        buildPhase: resources
        optional: true
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: "2"  # iPad only
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        # Include paths
        HEADER_SEARCH_PATHS:
          - $(PROJECT_DIR)/../vendor/imgui
          - $(PROJECT_DIR)/../vendor/imgui/backends
          - $(PROJECT_DIR)/../vendor/flecs/distr
          - $(PROJECT_DIR)/../vendor
          - $(PROJECT_DIR)/../vulkan
          - $(PROJECT_DIR)/Frameworks/include
          - $(PROJECT_DIR)/Frameworks/include/SDL3
          - $(PROJECT_DIR)/Frameworks/include/vulkan
          - $(PROJECT_DIR)/Frameworks/include/MoltenVK
          # jank headers (uses JANK_SRC env var, substituted at xcodegen time)
          - ${JANK_SRC}/include/cpp
          - ${JANK_SRC}/src/cpp
          - ${JANK_SRC}/third-party/immer
          - ${JANK_SRC}/third-party/bdwgc/include
          - ${JANK_SRC}/third-party/bpptree/include
          - ${JANK_SRC}/third-party/boost-preprocessor/include
          - ${JANK_SRC}/third-party/boost-multiprecision/include
          - ${JANK_SRC}/third-party/folly
          - ${JANK_SRC}/third-party/stduuid/include
        FRAMEWORK_SEARCH_PATHS:
          - $(PROJECT_DIR)/Frameworks
        LIBRARY_SEARCH_PATHS:
          - $(PROJECT_DIR)/build-$(PLATFORM_NAME)
          # jank libraries (uses JANK_SRC env var, substituted at xcodegen time)
          - ${JANK_SRC}/build-ios-simulator
          - ${JANK_SRC}/build-ios-simulator/third-party/bdwgc
          - ${JANK_SRC}/build-ios
          - ${JANK_SRC}/build-ios/third-party/bdwgc
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/Frameworks"
        # Linker flags
        OTHER_LDFLAGS:
          - "-framework Metal"
          - "-framework MetalKit"
          - "-framework QuartzCore"
          - "-framework UIKit"
          - "-framework Foundation"
          - "-framework CoreGraphics"
          - "-framework CoreVideo"
          - "-framework AVFoundation"
          - "-framework GameController"
          - "-framework CoreHaptics"
          - "-framework CoreMotion"
          - "-framework IOSurface"
          - "-framework IOKit"
          - "-lc++"
          # jank runtime libraries
          - "-ljank"
          - "-ljankzip"
          - "-lgc"
          # All AOT-compiled jank modules (core + user) bundled into one library
          # This is auto-generated by build_ios_jank_aot.sh - no manual updates needed!
          - "-lvybe_aot"
        # Code signing - automatic for device, none for simulator
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGNING_ALLOWED: "YES"
    dependencies:
      - framework: Frameworks/MoltenVK.xcframework
        embed: true
      - framework: Frameworks/SDL3.xcframework
        embed: true
    preBuildScripts:
      - name: Compile Shaders
        script: |
          echo "Checking shaders..."
          SHADER_DIR="${PROJECT_DIR}/../vulkan_kim"
          if command -v glslangValidator &> /dev/null; then
            for shader in "$SHADER_DIR"/*.comp; do
              if [ -f "$shader" ]; then
                spv="${shader%.comp}.spv"
                if [ ! -f "$spv" ] || [ "$shader" -nt "$spv" ]; then
                  echo "Compiling $(basename "$shader")..."
                  glslangValidator -V "$shader" -o "$spv"
                fi
              fi
            done
          fi

schemes:
  SdfViewerMobile:
    build:
      targets:
        SdfViewerMobile: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
