# XcodeGen project specification for SDF Viewer Mobile
# Generate Xcode project with: xcodegen generate
# Install xcodegen: brew install xcodegen

name: SdfViewerMobile

options:
  bundleIdPrefix: com.vybe
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: SdfViewerMobile
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_BITCODE: NO
    CLANG_CXX_LANGUAGE_STANDARD: c++17
    CLANG_CXX_LIBRARY: libc++
    GCC_PREPROCESSOR_DEFINITIONS:
      - VK_USE_PLATFORM_IOS_MVK=1
      - VK_USE_PLATFORM_METAL_EXT=1

targets:
  SdfViewerMobile:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: main.mm
        compilerFlags: ["-x", "objective-c++"]
      - path: sdf_viewer_ios.mm
        compilerFlags: ["-x", "objective-c++"]
      # ImGui sources
      - path: ../vendor/imgui/imgui.cpp
      - path: ../vendor/imgui/imgui_draw.cpp
      - path: ../vendor/imgui/imgui_widgets.cpp
      - path: ../vendor/imgui/imgui_tables.cpp
      - path: ../vendor/imgui/backends/imgui_impl_vulkan.cpp
      - path: ../vendor/imgui/backends/imgui_impl_sdl3.cpp
      # STB implementation
      - path: ../vulkan/stb_impl.c
      # Resources (bundled with app)
      - path: LaunchScreen.storyboard
        buildPhase: resources
      - path: vulkan_kim
        buildPhase: resources
        type: folder
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: "2"  # iPad only
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        # Include paths
        HEADER_SEARCH_PATHS:
          - $(PROJECT_DIR)/../vendor/imgui
          - $(PROJECT_DIR)/../vendor/imgui/backends
          - $(PROJECT_DIR)/../vendor/flecs/distr
          - $(PROJECT_DIR)/../vendor
          - $(PROJECT_DIR)/../vulkan
          - $(PROJECT_DIR)/Frameworks/include
          - $(PROJECT_DIR)/Frameworks/include/SDL3
          - $(PROJECT_DIR)/Frameworks/include/vulkan
          - $(PROJECT_DIR)/Frameworks/include/MoltenVK
        FRAMEWORK_SEARCH_PATHS:
          - $(PROJECT_DIR)/Frameworks
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/Frameworks"
        # Linker flags
        OTHER_LDFLAGS:
          - "-framework Metal"
          - "-framework MetalKit"
          - "-framework QuartzCore"
          - "-framework UIKit"
          - "-framework Foundation"
          - "-framework CoreGraphics"
          - "-framework CoreVideo"
          - "-framework AVFoundation"
          - "-framework GameController"
          - "-framework CoreHaptics"
          - "-framework CoreMotion"
          - "-framework IOSurface"
          - "-framework IOKit"
          - "-lc++"
        # Code signing for simulator testing
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
    dependencies:
      - framework: Frameworks/MoltenVK.xcframework
        embed: true
      - framework: Frameworks/SDL3.xcframework
        embed: true
    preBuildScripts:
      - name: Compile Shaders
        script: |
          echo "Checking shaders..."
          SHADER_DIR="${PROJECT_DIR}/../vulkan_kim"
          if command -v glslangValidator &> /dev/null; then
            for shader in "$SHADER_DIR"/*.comp; do
              if [ -f "$shader" ]; then
                spv="${shader%.comp}.spv"
                if [ ! -f "$spv" ] || [ "$shader" -nt "$spv" ]; then
                  echo "Compiling $(basename "$shader")..."
                  glslangValidator -V "$shader" -o "$spv"
                fi
              fi
            done
          fi

schemes:
  SdfViewerMobile:
    build:
      targets:
        SdfViewerMobile: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
