// libfive mesh generation test using C++ API
// Compile: clang++ -std=c++17 -I../vendor/libfive/libfive/include -I/opt/homebrew/include -I/opt/homebrew/opt/eigen/include/eigen3 -L../vendor/libfive/build/libfive/src -lfive libfive_test2.cpp -o libfive_test2

#include <iostream>
#include <fstream>

#include "libfive/tree/tree.hpp"
#include "libfive/render/brep/mesh.hpp"
#include "libfive/render/brep/settings.hpp"
#include "libfive/render/brep/region.hpp"
#include "libfive/eval/evaluator.hpp"

using namespace libfive;

// Export mesh to OBJ file
bool exportOBJ(const char* filename, const Mesh* mesh) {
    if (!mesh) return false;

    std::ofstream file(filename);
    if (!file.is_open()) return false;

    file << "# Generated by libfive mesh test (C++ API)\n";
    file << "# Vertices: " << mesh->verts.size() << "\n";
    file << "# Triangles: " << mesh->branes.size() << "\n\n";

    // Write vertices
    for (const auto& v : mesh->verts) {
        file << "v " << v.x() << " " << v.y() << " " << v.z() << "\n";
    }

    file << "\n";

    // Write faces (OBJ uses 1-based indexing)
    for (const auto& t : mesh->branes) {
        file << "f " << (t(0) + 1) << " " << (t(1) + 1) << " " << (t(2) + 1) << "\n";
    }

    file.close();
    return true;
}

int main() {
    std::cout << "libfive C++ API test\n\n";

    // Create a sphere SDF using C++ Tree API
    auto x = Tree::X();
    auto y = Tree::Y();
    auto z = Tree::Z();

    // sqrt(x^2 + y^2 + z^2) - 1  (sphere of radius 1)
    Tree sphere = sqrt(square(x) + square(y) + square(z)) - 1.0f;

    std::cout << "Created sphere SDF\n\n";

    // Test evaluation using Evaluator
    Evaluator eval(sphere);
    std::cout << "Evaluation test:\n";
    std::cout << "  f(0,0,0) = " << eval.value({0, 0, 0}) << " (expected: -1)\n";
    std::cout << "  f(1,0,0) = " << eval.value({1, 0, 0}) << " (expected: 0)\n";
    std::cout << "  f(2,0,0) = " << eval.value({2, 0, 0}) << " (expected: 1)\n\n";

    // Render mesh using C++ API
    std::cout << "Rendering mesh...\n";

    Region<3> region({-2.0f, -2.0f, -2.0f}, {2.0f, 2.0f, 2.0f});

    BRepSettings settings;
    settings.workers = 1;  // Single-threaded for stability
    settings.min_feature = 0.1;  // Minimum feature size

    auto mesh = Mesh::render(sphere, region, settings);

    if (mesh) {
        std::cout << "Mesh generated successfully!\n";
        std::cout << "  Vertices: " << mesh->verts.size() << "\n";
        std::cout << "  Triangles: " << mesh->branes.size() << "\n";

        // Export to OBJ
        if (mesh->branes.size() > 0) {
            if (exportOBJ("sphere_test2.obj", mesh.get())) {
                std::cout << "Exported to sphere_test2.obj\n";
            }

            // Also save as STL
            if (mesh->saveSTL("sphere_test2.stl")) {
                std::cout << "Exported to sphere_test2.stl\n";
            }
        } else {
            std::cout << "No triangles to export\n";
        }
    } else {
        std::cout << "ERROR: Failed to generate mesh\n";
        return 1;
    }

    std::cout << "\nDone!\n";
    return 0;
}
