// libfive mesh generation test
// Compile: clang++ -std=c++17 -I../vendor/libfive/libfive/include -L../vendor/libfive/build/libfive/src -lfive libfive_test.cpp -o libfive_test
// Run: DYLD_LIBRARY_PATH=../vendor/libfive/build/libfive/src ./libfive_test

#include <iostream>
#include <fstream>
#include "libfive.h"

// Export mesh to OBJ file
bool exportOBJ(const char* filename, libfive_mesh* mesh) {
    if (!mesh) return false;

    std::ofstream file(filename);
    if (!file.is_open()) return false;

    file << "# Generated by libfive mesh test\n";
    file << "# Vertices: " << mesh->vert_count << "\n";
    file << "# Triangles: " << mesh->tri_count << "\n\n";

    // Write vertices
    for (uint32_t i = 0; i < mesh->vert_count; i++) {
        file << "v " << mesh->verts[i].x << " "
             << mesh->verts[i].y << " "
             << mesh->verts[i].z << "\n";
    }

    file << "\n";

    // Write faces (OBJ uses 1-based indexing)
    for (uint32_t i = 0; i < mesh->tri_count; i++) {
        file << "f " << (mesh->tris[i].a + 1) << " "
             << (mesh->tris[i].b + 1) << " "
             << (mesh->tris[i].c + 1) << "\n";
    }

    file.close();
    return true;
}

int main() {
    std::cout << "libfive version: " << libfive_git_version() << "\n";
    std::cout << "libfive revision: " << libfive_git_revision() << "\n\n";

    // Create a simple sphere SDF: sqrt(x^2 + y^2 + z^2) - 1
    libfive_tree x = libfive_tree_x();
    libfive_tree y = libfive_tree_y();
    libfive_tree z = libfive_tree_z();

    // x*x + y*y + z*z
    int mul_op = libfive_opcode_enum("mul");
    int add_op = libfive_opcode_enum("add");
    int sub_op = libfive_opcode_enum("sub");
    int sqrt_op = libfive_opcode_enum("sqrt");

    libfive_tree xx = libfive_tree_binary(mul_op, x, x);
    libfive_tree yy = libfive_tree_binary(mul_op, y, y);
    libfive_tree zz = libfive_tree_binary(mul_op, z, z);

    libfive_tree sum_xy = libfive_tree_binary(add_op, xx, yy);
    libfive_tree sum_xyz = libfive_tree_binary(add_op, sum_xy, zz);

    // sqrt(x^2 + y^2 + z^2)
    libfive_tree dist = libfive_tree_unary(sqrt_op, sum_xyz);

    // sqrt(x^2 + y^2 + z^2) - 1  (sphere of radius 1)
    libfive_tree one = libfive_tree_const(1.0f);
    libfive_tree sphere = libfive_tree_binary(sub_op, dist, one);

    std::cout << "Created sphere SDF tree\n";

    // Print the tree
    char* str = libfive_tree_print(sphere);
    std::cout << "Tree: " << str << "\n\n";
    libfive_free_str(str);

    // Test evaluation at a few points
    libfive_vec3 p1 = {0, 0, 0};      // Inside, should be -1
    libfive_vec3 p2 = {1, 0, 0};      // On surface, should be 0
    libfive_vec3 p3 = {2, 0, 0};      // Outside, should be 1

    std::cout << "Evaluation test:\n";
    std::cout << "  f(0,0,0) = " << libfive_tree_eval_f(sphere, p1) << " (expected: -1)\n";
    std::cout << "  f(1,0,0) = " << libfive_tree_eval_f(sphere, p2) << " (expected: 0)\n";
    std::cout << "  f(2,0,0) = " << libfive_tree_eval_f(sphere, p3) << " (expected: 1)\n\n";

    // Render mesh
    std::cout << "Rendering mesh...\n";

    libfive_region3 region = {
        {-2.0f, 2.0f},  // X
        {-2.0f, 2.0f},  // Y
        {-2.0f, 2.0f}   // Z
    };

    float resolution = 0.05f;  // Smaller = more detail (was 0.1)

    // Try saving directly to STL first (using libfive's built-in)
    std::cout << "Saving to sphere_test.stl using libfive...\n";
    bool saved = libfive_tree_save_mesh(sphere, region, resolution, "sphere_test.stl");
    std::cout << "Save result: " << (saved ? "success" : "failed") << "\n\n";

    // Also try render_mesh
    libfive_mesh* mesh = libfive_tree_render_mesh(sphere, region, resolution);

    if (mesh) {
        std::cout << "Mesh generated successfully!\n";
        std::cout << "  Vertices: " << mesh->vert_count << "\n";
        std::cout << "  Triangles: " << mesh->tri_count << "\n";

        // Export to OBJ
        if (mesh->tri_count > 0) {
            if (exportOBJ("sphere_test.obj", mesh)) {
                std::cout << "Exported to sphere_test.obj\n";
            }
        } else {
            std::cout << "No triangles to export\n";
        }

        libfive_mesh_delete(mesh);
    } else {
        std::cout << "ERROR: Failed to generate mesh\n";
        return 1;
    }

    // Cleanup trees
    libfive_tree_delete(sphere);
    libfive_tree_delete(one);
    libfive_tree_delete(dist);
    libfive_tree_delete(sum_xyz);
    libfive_tree_delete(sum_xy);
    libfive_tree_delete(zz);
    libfive_tree_delete(yy);
    libfive_tree_delete(xx);
    libfive_tree_delete(z);
    libfive_tree_delete(y);
    libfive_tree_delete(x);

    std::cout << "\nDone!\n";
    return 0;
}
